appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: GfJesRKV8jwmkM8V04KoudG68sH6JFjSvl8DzJaHJ851ZDqmRsHTPCuEskGlLTBPvjn0gvC8sL0/tSqVcHzSlGipxCH18zyrIm79eGrbcjAh9wEtCZi47lu1pVIG4EQnCoiL/WX3+H8+WmpwZCKFjrxyKTiioN+pq7RbuUHeo4/UU0Wu/eA+sSdJ+FDiVkrlCWEreCFEmjXgbX4uZXJZzsA1hiRskcV25cEJi7ExDaFd+o8vRt3Mxai9v7WgHtth8c8pTYNIe8QBHcHsLIcRZ8D3AqG2bJEE7HZ4httRzoMpNBi30vqP/qykOrzmRlQOng12V7Lq3G0gNr6Zs8c9FUSv//fv99MTbIrfg8i0FPesQxF8d+dPC2tzIlgg/9DUxlKlLU7UqM3i+YwReShqlziRFsDzLTtAL028pKCvVcO/y5j3ZM39OBN8av1XhfTugInBHRdSiNsVY0S3UF5gCJlijzcdc22TIfpNwbs11qUB1V/37uG0PkzRIiuG+JUoN+PqzLzOYenJgOQ/JMucbRlnbu42+tA7gGDfD1DZO8ha5jKhgnsrj7JOUTAGkskHIjtJyU5DSSrLH/Bgibz6j8y1waKp9QWsihgaQaJqwSND/7BaQiE2DNPTb7bmOnhGdsu3V0hkm46u8awcFHll2GzTWgF/bqVfwijZr8hPtUw=}
