travis:
  secure:
    BINSTAR_TOKEN: sfCcKZsj05mrBS/s7d77ZbGEG1XnG5jtLJ4oY3ze9EPIhMT5Tas0FS2E0KOB3Xs+6tdy3ohnH5kyrIczPIsEowCBcVcCe4XDAegtGj7FcrQ6KoyhndHxqXALoYOi5QewRxK648hSdqNdN5Jp2D15oQJd04TJIwN72/4xGL5RKehwgXHrpbcBzk0CgBHK9u1UhCc81iUICoX+lgdT5aaP4Us/Ug7GkSYi3E3XmuPlWj/PHjSOxv8oy8jpw0mmDNxGeq1OzU4RTcBH4XBTHF4RCKaYoCN4qpsouSSPNd+pcb/Oslp2beKZg3oIA9+bBCr+dAL8/Yy0kCt9G21LYQzO3IL6vYAYKS6UYTKY2TdxoynHwfKaT7B345wl+QQriPT7yED/Fvp0OHqwhLTax5DZP2R2AsvmYiBFHlFUCE1wrldxNCZTcbDjoirOAHfQXSN+R95NBIpGfkHPT8e475AYEZ5J8bHNoxvcFg8Kwt0cagmPX66Ak/aOIFVgpZZow08X19bfhToqwaaOUGgV+nGBdmTaGxw6OxP4RgyT3784s8Hlwho8vMQcrMcxtCOH/TML9cFluahhgKX43MhJiqRmRnt+Q/B+zZt5zj7RsoR2KwGKCe3q4MXRnOfycdHnfgNja9kWNr60I8tCpNhjDpp80BCmkzp9pnweqCRU52hFsFw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
